- hosts: "{{ lookup('env','ANSIBLE_HOST_GROUP') or 'localhost' }}"
  become: "{{ lookup('env', 'ANSIBLE_BECOME') or 'False' }}"
  user: "{{ lookup('env', 'ANSIBLE_REMOTE_USER') or 'root' }}"
  vars_files:
    - ./vars/main.yml
    - ./vars/vault.yml
  tasks:
    # - import_tasks: mytasks.yml
