- hosts: exampleservers
  become: True
  user: root
  vars_files:
    - ./vars/main.yml
    - ./vars/vault.yml

  tasks:
    - import_tasks: prepare.yml
    - import_tasks: datasheet.yml
    - import_tasks: timemap.yml
      import_tasks: nginx.yml

    - name: update sheets
      command: curl http://localhost:{{ datasheet.port }}/api/update

    - name: restart nginx
      service: name=nginx state=restarted enabled=yes
