- hosts: localhost
  vars:
    aws_access_key: "{{ lookup('env','AWS_ACCESS_KEY_ID') }}"
    aws_secret_key: "{{ lookup('env','AWS_SECRET_ACCESS_KEY') }}"
    spaces_endpoint: https://ams3.digitaloceanspaces.com
    bucket_name: "{{ lookup('env','BUCKET_NAME') }}"
    asset_name: "{{ lookup('env','FOLDER') }}"
    region_name: nyc3
    local_folder: "{{ lookup('env', 'LOCAL_FOLDER') }}"
  tasks:
    - name: Upload files
      s3_sync:
        aws_access_key: '{{ aws_access_key }}'
        aws_secret_key: '{{ aws_secret_key }}'
        ec2_url: '{{ spaces_endpoint }}'
        region: '{{ region_name }}'
        bucket: '{{ bucket_name }}'
        file_root: '{{ local_folder }}'
        key_prefix: '{{ asset_name }}'
        permission: public-read
